import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

let links = [
  { href: '/journal', label: 'Journal' },
  { href: '/sign-up', label: 'Sign Up' },
  { href: '/sign-in', label: 'Sign In' },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="w-screen h-screen">
            <nav className="bg-slate-800 text-white w-full h-16 absolute flex justify-between items-center">
              <h3 className="font-extrabold font-mono text-3xl ml-10">
                Emotrack
              </h3>
              <ul className="flex justify-end items-center mx-16">
                {links.map((link) => (
                  <li
                    key={link.href}
                    className="px-7 mx-5 cursor-pointer py-2 text-xl border border-gray-300 rounded-full"
                  >
                    <Link href={link.href}>{link.label}</Link>
                  </li>
                ))}
              </ul>
            </nav>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
